version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgresql
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=carcatalog
    restart: unless-stopped
  # APP*****************************************
  carcatalogapi:
    image: carcatalogapi:latest
    network_mode: bridge
    container_name: carcatalogapi
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data: